// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueNhNu_VM4QBHJRUo4cJFSVee9tA1gF0',
    appId: '1:1087645995536:web:c2b33b9b6a38cab541f095',
    messagingSenderId: '1087645995536',
    projectId: 'safepackage-5e3ee',
    authDomain: 'safepackage-5e3ee.firebaseapp.com',
    storageBucket: 'safepackage-5e3ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4QvOX5uG51SUKSJQ14987ZuIrk2cmvA',
    appId: '1:1087645995536:android:6082e9d94efcfd1041f095',
    messagingSenderId: '1087645995536',
    projectId: 'safepackage-5e3ee',
    storageBucket: 'safepackage-5e3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4r4u9hgJV3Te3pn2pdTrQoml5t5OUd0A',
    appId: '1:1087645995536:ios:70aac2a43912d14241f095',
    messagingSenderId: '1087645995536',
    projectId: 'safepackage-5e3ee',
    storageBucket: 'safepackage-5e3ee.appspot.com',
    iosBundleId: 'com.example.safepackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4r4u9hgJV3Te3pn2pdTrQoml5t5OUd0A',
    appId: '1:1087645995536:ios:17b6eb0c1930102e41f095',
    messagingSenderId: '1087645995536',
    projectId: 'safepackage-5e3ee',
    storageBucket: 'safepackage-5e3ee.appspot.com',
    iosBundleId: 'com.example.safepackage.RunnerTests',
  );
}
